version: '3'

services:
  db:
    environment:
      POSTGRES_DB: phone
      POSTGRES_PASSWORD: postgres
    image: postgres:12-alpine
    ports:
      - 5433:5432
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

